name: hazus_twopager_env
channels:
  - nhrap
  - nsls2forge
  - conda-forge
  - defaults
dependencies:
  - fiona=1.8.17=py39h6119223_1
  - geopandas=0.8.2=pyhd8ed1ab_0
  - numpy=1.21.2=py39h6635163_0
  - pandas=1.3.2=py39h2e25243_0
  - paramiko=2.7.2=pyh9f0ad1d_0
  - pillow=8.4.0=py39hd45dc43_0
  - pyodbc=4.0.30=py39h415ef7b_1
  - shapely=1.7.1=py39hdfdf89f_1